version: '5'

services:

  mysql:
    image: mysql
    container_name: hackathon-mysql
    restart: always
    volumes:
      - database:/data/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
      MYSQL_PASSWORD: root

  hackathon:
    image: kalchenkoserhii/hackathon
    ports:
      - 8080:8080
#    depends_on:
#      mysql:
#        condition: service_started
    links:
      - mysql
    restart: unless-stopped

volumes:
  database: